### ISSUE TITLE
Also support GitHub Actions, GitHub Workflows

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#54]
The presence of the env `GITHUB_WORKFLOW` signals that we are running in a GitHub Action. We should do some automatic similar to what we are doing for Travis CI.

https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

**Comment by probonopd** [comment]
GitHub automatically creates a `GITHUB_TOKEN` secret to use in your workflow. You can use the `GITHUB_TOKEN` to authenticate in a workflow run.

https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by probonopd** [comment]
Example: https://github.com/probonopd/Akira/actions

**Comment by probonopd** [comment]
In order to generate updateinformation, we would probably have to internalize what

```
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: continuous
        prerelease: true
        draft: false
        files: |
          Akira*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
```

does.
